# Generated by Django 3.1.6 on 2021-02-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palmapplicant',
            old_name='brith',
            new_name='birth',
        ),
    ]
