# Generated by Django 4.2.19 on 2025-02-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0004_alter_filterscheme_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filterscheme",
            options={"verbose_name": "筛选方案", "verbose_name_plural": "筛选方案"},
        ),
    ]
