# Generated by Django 4.2.19 on 2025-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("推免硕士", "推免硕士"),
                            ("考研硕士", "考研硕士"),
                            ("博士", "博士"),
                            ("直博", "直博"),
                        ],
                        max_length=20,
                        verbose_name="招生类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
            ],
            options={
                "verbose_name": "招生时间配置",
                "verbose_name_plural": "招生时间配置",
                "unique_together": {("year", "type")},
            },
        ),
    ]
