# Generated by Django 4.2.19 on 2025-04-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("date", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissiondate",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="admissiondate",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
    ]
