# Generated by Django 3.1.6 on 2021-02-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalmApplicant',
            fields=[
                ('objid', models.AutoField(primary_key=True, serialize=False)),
                ('name_input', models.CharField(max_length=32, verbose_name='姓名')),
                ('grade_input', models.IntegerField(verbose_name='专业排名')),
                ('sex_input', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('gradepeople_input', models.IntegerField(verbose_name='专业人数')),
                ('brith', models.CharField(default='生日', max_length=100, verbose_name='出生年月')),
                ('major_input', models.CharField(default='专业', max_length=100, verbose_name='专业')),
                ('home_input', models.CharField(default='籍贯', max_length=100, verbose_name='籍贯')),
                ('university_input', models.CharField(default='院校', max_length=100, verbose_name='院校')),
                ('phonenumber_input', models.CharField(default='手机号', max_length=100, verbose_name='手机号')),
                ('email_input', models.EmailField(default='123@seu.edu.cn', max_length=254, verbose_name='邮箱')),
                ('registrationtype_input', models.CharField(default='类型', max_length=100, verbose_name='报名类型')),
                ('ajustment_input', models.BooleanField(default=1)),
                ('tutor_input', models.CharField(default='导师', max_length=100, verbose_name='导师')),
                ('resume_input', models.CharField(default='个人简历', max_length=500, verbose_name='个人简历')),
                ('statement_input', models.CharField(default='个人陈述', max_length=500, verbose_name='个人陈述')),
                ('researchplan_input', models.CharField(default='研究计划', max_length=500, verbose_name='研究计划')),
            ],
        ),
    ]
