# Generated by Django 2.2.5 on 2021-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0007_auto_20210522_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmapplicant',
            name='researchplan_input',
            field=models.CharField(default='研究计划', max_length=1000, verbose_name='研究计划'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='statement_input',
            field=models.CharField(default='个人陈述', max_length=1000, verbose_name='个人陈述'),
        ),
    ]
