# Generated by Django 4.2.19 on 2025-02-23 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="申请者ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="文件类型"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "uploader",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="上传者"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件",
                "db_table": "files",
            },
        ),
    ]
