# Generated by Django 4.2.19 on 2025-03-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_file_file_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_category",
        ),
    ]
