# Generated by Django 4.2.19 on 2025-03-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_remove_file_file_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_resume",
            field=models.BooleanField(default=False, verbose_name="是否为简历文件"),
        ),
    ]
