# Generated by Django 4.2.19 on 2025-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_file_is_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="download_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="下载地址"
            ),
        ),
    ]
