# Generated by Django 3.1.6 on 2021-05-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0004_auto_20210216_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palmapplicant',
            old_name='birth',
            new_name='birthday',
        ),
        migrations.RemoveField(
            model_name='palmapplicant',
            name='home_input',
        ),
        migrations.RemoveField(
            model_name='palmapplicant',
            name='resume_input',
        ),
        migrations.RemoveField(
            model_name='palmapplicant',
            name='tutor_input',
        ),
        migrations.RemoveField(
            model_name='palmapplicant',
            name='university_input',
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_grade1',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖等级1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_grade2',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖等级2'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_grade3',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖等级3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_grade4',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖等级4'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_grade5',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖等级5'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_name1',
            field=models.CharField(default='0', max_length=100, verbose_name='奖项1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_name2',
            field=models.CharField(default='0', max_length=100, verbose_name='奖项2'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_name3',
            field=models.CharField(default='0', max_length=100, verbose_name='奖项3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_name4',
            field=models.CharField(default='0', max_length=100, verbose_name='奖项4'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='award_name5',
            field=models.CharField(default='0', max_length=100, verbose_name='奖项5'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='city',
            field=models.CharField(default='城市', max_length=100, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='district',
            field=models.CharField(default='街道', max_length=100, verbose_name='街道'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='journal_name1',
            field=models.CharField(default='0', max_length=100, verbose_name='期刊会议名1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='journal_name2',
            field=models.CharField(default='0', max_length=100, verbose_name='期刊会议名1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='journal_name3',
            field=models.CharField(default='0', max_length=100, verbose_name='期刊会议名3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='master_university_input',
            field=models.CharField(choices=[('0', '北京大学'), ('1', '中国人民大学'), ('2', '清华大学'), ('3', '北京航空航天大学'), ('4', '北京理工大学'), ('5', '中国农业大学'), ('6', '北京师范大学'), ('7', '中央民族大学'), ('8', '南开大学'), ('9', '天津大学'), ('10', '大连理工大学'), ('11', '吉林大学'), ('12', '哈尔滨工业大学'), ('13', '复旦大学'), ('14', '同济大学'), ('15', '上海交通大学'), ('16', '华东师范大学'), ('17', '南京大学'), ('18', '东南大学'), ('19', '浙江大学'), ('20', '中国科学技术大学'), ('21', '厦门大学'), ('22', '山东大学'), ('23', '中国海洋大学'), ('24', '武汉大学'), ('25', '华中科技大学'), ('26', '中南大学'), ('27', '中山大学'), ('28', '华南理工大学'), ('29', '四川大学'), ('30', '重庆大学'), ('31', '电子科技大学'), ('32', '西安交通大学'), ('33', '西北工业大学'), ('34', '兰州大学'), ('35', '中国人民解放军国防科技大学'), ('36', '东北大学'), ('37', '郑州大学'), ('38', '湖南大学'), ('39', '云南大学'), ('40', '西北农林科技大学'), ('41', '新疆大学'), ('42', '北京邮电大学'), ('43', '北京交通大学'), ('44', '西安电子科技大学'), ('45', '解放军信息工程大学'), ('46', '北京工业大学'), ('47', '北京科技大学'), ('48', '哈尔滨工程大学'), ('49', '南京航空航天大学'), ('50', '南京理工大学'), ('51', '杭州电子科技大学'), ('52', '合肥工业大学'), ('53', '西南交通大学'), ('54', '重庆邮电大学'), ('55', '解放军理工大学'), ('56', '天津理工大学'), ('57', '山西大学'), ('58', '大连海事大学'), ('59', '长春理工大学'), ('60', '哈尔滨理工大学'), ('61', '燕山大学'), ('62', '华东理工大学'), ('63', '上海大学'), ('64', '苏州大学'), ('65', '中国矿业大学'), ('66', '河海大学'), ('67', '江苏大学'), ('68', '南京信息工程大学'), ('69', '浙江工业大学'), ('70', '安徽大学'), ('71', '中国地质大学'), ('72', '武汉理工大学'), ('73', '暨南大学'), ('74', '深圳大学'), ('75', '西南大学'), ('76', '火箭军工程大学'), ('77', '西北大学'), ('78', '南京邮电大学'), ('79', '江南大学')], default='硕士学校', max_length=100, verbose_name='硕士院校'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='mastertutor_input',
            field=models.CharField(default='本科生不填写', max_length=100, verbose_name='硕士导师'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='paper_name1',
            field=models.CharField(default='0', max_length=500, verbose_name='论文1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='paper_name2',
            field=models.CharField(default='0', max_length=500, verbose_name='论文1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='paper_name3',
            field=models.CharField(default='0', max_length=500, verbose_name='论文3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='photo',
            field=models.ImageField(default='0', upload_to='img/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='province',
            field=models.CharField(default='省份', max_length=100, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_award1',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖时间1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_award2',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖时间2'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_award3',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖时间3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_award4',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖时间4'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_award5',
            field=models.CharField(default='0', max_length=100, verbose_name='获奖时间5'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_paper1',
            field=models.CharField(default='0', max_length=100, verbose_name='论文发表时间1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_paper2',
            field=models.CharField(default='0', max_length=100, verbose_name='论文发表时间1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='time_paper3',
            field=models.CharField(default='0', max_length=100, verbose_name='论文发表时间3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='tutor_input_first',
            field=models.CharField(choices=[('0', '耿新'), ('1', '张敏灵'), ('2', '周德宇'), ('3', '薛晖'), ('4', '张宇'), ('5', '闫亚萍'), ('6', '宋沫飞'), ('7', '祁磊'), ('8', '徐宁'),('9','魏秀参'),('10','贾育衡'),('11','周毅'),('12','陈浩'),('13','李竹颖'),('14','杨旭'),('15','魏通'),('16','时霄'),('17','王洪松'),('18','乔伊果'),('19','方鹏飞'),('20','吕佳祺'),('21','王靖'),('22','石楚涵')], default='导师1', max_length=100, verbose_name='导师1'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='tutor_input_second',
            field=models.CharField(choices=[('0', '耿新'), ('1', '张敏灵'), ('2', '周德宇'), ('3', '薛晖'), ('4', '张宇'), ('5', '闫亚萍'), ('6', '宋沫飞'), ('7', '祁磊'), ('8', '徐宁'),('9','魏秀参'),('10','贾育衡'),('11','周毅'),('12','陈浩'),('13','李竹颖'),('14','杨旭'),('15','魏通'),('16','时霄'),('17','王洪松'),('18','乔伊果'),('19','方鹏飞'),('20','吕佳祺'),('21','王靖'),('22','石楚涵')], default='导师2', max_length=100, verbose_name='导师2'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='tutor_input_third',
            field=models.CharField(choices=[('0', '耿新'), ('1', '张敏灵'), ('2', '周德宇'), ('3', '薛晖'), ('4', '张宇'), ('5', '闫亚萍'), ('6', '宋沫飞'), ('7', '祁磊'), ('8', '徐宁'),('9','魏秀参'),('10','贾育衡'),('11','周毅'),('12','陈浩'),('13','李竹颖'),('14','杨旭'),('15','魏通'),('16','时霄'),('17','王洪松'),('18','乔伊果'),('19','方鹏飞'),('20','吕佳祺'),('21','王靖'),('22','石楚涵')], default='导师3', max_length=100, verbose_name='导师3'),
        ),
        migrations.AddField(
            model_name='palmapplicant',
            name='undergraduate_university_input',
            field=models.CharField(choices=[('0', '北京大学'), ('1', '中国人民大学'), ('2', '清华大学'), ('3', '北京航空航天大学'), ('4', '北京理工大学'), ('5', '中国农业大学'), ('6', '北京师范大学'), ('7', '中央民族大学'), ('8', '南开大学'), ('9', '天津大学'), ('10', '大连理工大学'), ('11', '吉林大学'), ('12', '哈尔滨工业大学'), ('13', '复旦大学'), ('14', '同济大学'), ('15', '上海交通大学'), ('16', '华东师范大学'), ('17', '南京大学'), ('18', '东南大学'), ('19', '浙江大学'), ('20', '中国科学技术大学'), ('21', '厦门大学'), ('22', '山东大学'), ('23', '中国海洋大学'), ('24', '武汉大学'), ('25', '华中科技大学'), ('26', '中南大学'), ('27', '中山大学'), ('28', '华南理工大学'), ('29', '四川大学'), ('30', '重庆大学'), ('31', '电子科技大学'), ('32', '西安交通大学'), ('33', '西北工业大学'), ('34', '兰州大学'), ('35', '中国人民解放军国防科技大学'), ('36', '东北大学'), ('37', '郑州大学'), ('38', '湖南大学'), ('39', '云南大学'), ('40', '西北农林科技大学'), ('41', '新疆大学'), ('42', '北京邮电大学'), ('43', '北京交通大学'), ('44', '西安电子科技大学'), ('45', '解放军信息工程大学'), ('46', '北京工业大学'), ('47', '北京科技大学'), ('48', '哈尔滨工程大学'), ('49', '南京航空航天大学'), ('50', '南京理工大学'), ('51', '杭州电子科技大学'), ('52', '合肥工业大学'), ('53', '西南交通大学'), ('54', '重庆邮电大学'), ('55', '解放军理工大学'), ('56', '天津理工大学'), ('57', '山西大学'), ('58', '大连海事大学'), ('59', '长春理工大学'), ('60', '哈尔滨理工大学'), ('61', '燕山大学'), ('62', '华东理工大学'), ('63', '上海大学'), ('64', '苏州大学'), ('65', '中国矿业大学'), ('66', '河海大学'), ('67', '江苏大学'), ('68', '南京信息工程大学'), ('69', '浙江工业大学'), ('70', '安徽大学'), ('71', '中国地质大学'), ('72', '武汉理工大学'), ('73', '暨南大学'), ('74', '深圳大学'), ('75', '西南大学'), ('76', '火箭军工程大学'), ('77', '西北大学'), ('78', '南京邮电大学'), ('79', '江南大学')], default='本科学校', max_length=100, verbose_name='院校'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='ajustment_input',
            field=models.CharField(default='0', max_length=10, verbose_name='服从调剂'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='email_input',
            field=models.EmailField(default='mail', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='grade_input',
            field=models.IntegerField(verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='registrationtype_input',
            field=models.CharField(choices=[('0', '硕士'), ('1', '博士'), ('2', '直博')], max_length=100, verbose_name='报名类型'),
        ),
    ]
