# Generated by Django 4.2.19 on 2025-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_login_days",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
