# Generated by Django 3.1.6 on 2021-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20210216_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmapplicant',
            name='sex_input',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='tutor_input',
            field=models.CharField(choices=[('0', '耿新'), ('1', '张敏灵'), ('2', '周德宇'), ('3', '薛晖'), ('4', '张宇'), ('5', '闫亚萍'), ('6', '宋沫飞'), ('7', '祁磊'), ('8', '徐宁'),('9','魏秀参'),('10','贾育衡'),('11','周毅'),('12','陈浩'),('13','李竹颖'),('14','杨旭'),('15','魏通'),('16','时霄'),('17','王洪松'),('18','乔伊果'),('19','方鹏飞'),('20','吕佳祺'),('21','王靖'),('22','石楚涵')], default='耿新', max_length=100, verbose_name='导师'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='university_input',
            field=models.CharField(choices=[('0', '东南大学'), ('1', '中国矿业大学'), ('2', '武汉理工大学'), ('3', '南京信息工程大学')], default='东南大学', max_length=100, verbose_name='院校'),
        ),
    ]
