# Generated by Django 2.2.5 on 2021-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20210521_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmapplicant',
            name='master_university_input',
            field=models.CharField(default='硕士学校', max_length=100, verbose_name='硕士院校'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='registrationtype_input',
            field=models.CharField(max_length=100, verbose_name='报名类型'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='tutor_input_first',
            field=models.CharField(default='导师1', max_length=100, verbose_name='导师1'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='tutor_input_second',
            field=models.CharField(default='导师2', max_length=100, verbose_name='导师2'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='tutor_input_third',
            field=models.CharField(default='导师3', max_length=100, verbose_name='导师3'),
        ),
        migrations.AlterField(
            model_name='palmapplicant',
            name='undergraduate_university_input',
            field=models.CharField(default='本科学校', max_length=100, verbose_name='本科院校'),
        ),
    ]
