# Generated by Django 4.2.19 on 2025-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="department",
            field=models.CharField(
                default="计算机学院、软件学院、东蒙联合研究生院",
                max_length=200,
                verbose_name="所属院系",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="research_direction",
            field=models.CharField(
                default="待定", max_length=200, verbose_name="研究方向"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="recruitment_type",
            field=models.CharField(max_length=50, verbose_name="招生类型"),
        ),
    ]
