# Generated by Django 4.2.19 on 2025-02-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0003_alter_admissionperiod_id_alter_major_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="奖项名称")),
                ("level", models.CharField(max_length=50, verbose_name="奖项等级")),
                ("category", models.CharField(max_length=50, verbose_name="奖项类别")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "奖项信息",
                "verbose_name_plural": "奖项信息",
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "年份信息",
                "verbose_name_plural": "年份信息",
            },
        ),
    ]
