# Generated by Django 4.2.19 on 2025-05-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0004_award_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
    ]
