# Generated by Django 4.2.19 on 2025-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student", models.CharField(max_length=100, verbose_name="学生姓名")),
                ("score_teacher1", models.FloatField(verbose_name="老师一打分")),
                ("score_teacher2", models.FloatField(verbose_name="老师二打分")),
                ("score_teacher3", models.FloatField(verbose_name="老师三打分")),
                (
                    "normalized_score",
                    models.FloatField(blank=True, null=True, verbose_name="归一化打分"),
                ),
                ("resume_score", models.FloatField(default=0, verbose_name="简历分数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "面试评分",
                "verbose_name_plural": "面试评分",
                "ordering": ["-normalized_score"],
            },
        ),
    ]
