# Generated by Django 5.1.4 on 2024-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
