# Generated by Django 4.2.19 on 2025-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="字段名称"
                    ),
                ),
                ("description", models.TextField(verbose_name="字段描述")),
                (
                    "showInTable",
                    models.BooleanField(default=True, verbose_name="在表格中显示"),
                ),
                (
                    "showInFilter",
                    models.BooleanField(default=True, verbose_name="在筛选中显示"),
                ),
                (
                    "showInApply",
                    models.BooleanField(default=True, verbose_name="在申请中显示"),
                ),
            ],
            options={
                "verbose_name": "字段",
                "verbose_name_plural": "字段",
                "db_table": "field",
            },
        ),
    ]
