# Generated by Django 4.2.19 on 2025-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0002_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="variableName",
            field=models.CharField(
                default="default_var", max_length=50, verbose_name="变量名"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
