# Generated by Django 4.2.19 on 2025-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0003_field_variablename_alter_field_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="showInDirectPhd",
            field=models.BooleanField(default=True, verbose_name="在直博申请中显示"),
        ),
        migrations.AddField(
            model_name="field",
            name="showInExamMaster",
            field=models.BooleanField(
                default=True, verbose_name="在考研硕士申请中显示"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="showInPhd",
            field=models.BooleanField(default=True, verbose_name="在博士申请中显示"),
        ),
        migrations.AddField(
            model_name="field",
            name="showInRecommendMaster",
            field=models.BooleanField(
                default=True, verbose_name="在推免硕士申请中显示"
            ),
        ),
    ]
