# Generated by Django 4.2.19 on 2025-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0004_field_showindirectphd_field_showinexammaster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="regionInForm",
            field=models.CharField(
                default="other", max_length=50, verbose_name="在表单中的区域"
            ),
        ),
    ]
