# Generated by Django 4.2.19 on 2025-02-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("apply", "0001_initial"),
        ("apply", "0002_apply_award1_awardname_apply_award1_awardtime_and_more"),
        ("apply", "0003_alter_apply_birthdate"),
        ("apply", "0004_apply_masteruniversitylevel_apply_universitylevel"),
        ("apply", "0005_alter_apply_id"),
        ("apply", "0006_apply_award1_awardranking_apply_award2_awardranking_and_more"),
        ("apply", "0007_apply_firstauthorpaperlevel_apply_istopclass_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="apply",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("graduationYear", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("birthDate", models.CharField(max_length=20)),
                ("photo", models.ImageField(upload_to="apply/")),
                ("university", models.CharField(max_length=50)),
                ("major", models.CharField(max_length=50)),
                ("majorCount", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("percentage", models.CharField(max_length=10)),
                ("masterUniversity", models.CharField(max_length=50)),
                ("masterMajor", models.CharField(max_length=50)),
                ("tutor", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("applicationType", models.CharField(max_length=50)),
                ("firstChoice", models.CharField(max_length=50)),
                ("secondChoice", models.CharField(max_length=50)),
                ("thirdChoice", models.CharField(max_length=50)),
                ("isAdjustable", models.BooleanField()),
                ("proofs", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                (
                    "award1_awardName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "award1_awardTime",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("award1_isLeader", models.BooleanField(blank=True, null=True)),
                (
                    "award1_levelRanking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "award2_awardName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "award2_awardTime",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("award2_isLeader", models.BooleanField(blank=True, null=True)),
                (
                    "award2_levelRanking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "award3_awardName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "award3_awardTime",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("award3_isLeader", models.BooleanField(blank=True, null=True)),
                (
                    "award3_levelRanking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "paper1_awardCategory",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "paper1_ccfLevel",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "paper1_journalConference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paper1_paperName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paper1_publicationTime",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "paper2_awardCategory",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "paper2_ccfLevel",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "paper2_journalConference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paper2_paperName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paper2_publicationTime",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "paper3_awardCategory",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "paper3_ccfLevel",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "paper3_journalConference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paper3_paperName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paper3_publicationTime",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "masterUniversityLevel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "universityLevel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "award1_awardRanking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "award2_awardRanking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "award3_awardRanking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "firstAuthorPaperLevel",
                    models.CharField(
                        blank=True,
                        help_text="第一作者论文等级",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "isTopClass",
                    models.BooleanField(default=False, help_text="是否为拔尖班"),
                ),
                (
                    "meetAwardRequirement",
                    models.BooleanField(default=False, help_text="是否满足奖项条件"),
                ),
                (
                    "meetPaperRequirement",
                    models.BooleanField(default=False, help_text="是否满足论文条件"),
                ),
                (
                    "meetScreeningRequirement",
                    models.BooleanField(default=False, help_text="是否满足筛选条件"),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
