# Generated by Django 5.1.4 on 2024-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='award1_awardName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award1_awardTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award1_isLeader',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award1_levelRanking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award2_awardName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award2_awardTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award2_isLeader',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award2_levelRanking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award3_awardName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award3_awardTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award3_isLeader',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='award3_levelRanking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper1_awardCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper1_ccfLevel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper1_journalConference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper1_paperName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper1_publicationTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper2_awardCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper2_ccfLevel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper2_journalConference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper2_paperName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper2_publicationTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper3_awardCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper3_ccfLevel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper3_journalConference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper3_paperName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='paper3_publicationTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
