# Generated by Django 5.1.2 on 2024-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0003_alter_apply_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="masterUniversityLevel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="universityLevel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
