# Generated by Django 5.1.2 on 2024-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0004_apply_masteruniversitylevel_apply_universitylevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
