# Generated by Django 5.1.2 on 2024-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0005_alter_apply_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="award1_awardRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_awardRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_awardRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
