# Generated by Django 4.2.19 on 2025-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0006_apply_award1_awardranking_apply_award2_awardranking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="firstAuthorPaperLevel",
            field=models.CharField(
                blank=True, help_text="第一作者论文等级", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="isTopClass",
            field=models.BooleanField(default=False, help_text="是否为拔尖班"),
        ),
        migrations.AddField(
            model_name="apply",
            name="meetAwardRequirement",
            field=models.BooleanField(default=False, help_text="是否满足奖项条件"),
        ),
        migrations.AddField(
            model_name="apply",
            name="meetPaperRequirement",
            field=models.BooleanField(default=False, help_text="是否满足论文条件"),
        ),
        migrations.AddField(
            model_name="apply",
            name="meetScreeningRequirement",
            field=models.BooleanField(default=False, help_text="是否满足筛选条件"),
        ),
    ]
