# Generated by Django 4.2.19 on 2025-02-17 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0008_remove_apply_applicationtype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apply",
            options={"verbose_name": "申请", "verbose_name_plural": "申请"},
        ),
        migrations.AddField(
            model_name="apply",
            name="_applicationType",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="报名类型"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award1_awardName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项一名称"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award1_awardRanking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项一获奖排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award1_awardTime",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项一获奖时间"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award1_isLeader",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项一是否负责人"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award1_levelRanking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项一等级排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award2_awardName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项二名称"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award2_awardRanking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项二获奖排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award2_awardTime",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项二获奖时间"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award2_isLeader",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项二是否负责人"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award2_levelRanking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项二等级排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award3_awardName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项三名称"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award3_awardRanking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项三获奖排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award3_awardTime",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项三获奖时间"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award3_isLeader",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项三是否负责人"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_award3_levelRanking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="奖项三等级排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_birthDate",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="出生年月"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="电子邮箱"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_firstAuthorLevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="第一作者论文等级"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_firstChoice",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="第一志愿"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_gender",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="性别"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_graduationYear",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="毕业年份"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_isAdjustable",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="是否服从调剂"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_isAwardCondition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="是否满足奖项条件"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_isFilterCondition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="是否满足筛选条件"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_isPaperCondition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="是否满足论文条件"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_isTopClass",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="是否为拔尖班"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_major",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="本科专业"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_majorCount",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="专业人数"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_masterMajor",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="硕士专业"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_masterUniversity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="硕士学校"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_masterUniversityLevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="硕士等级"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="姓名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper1_awardCategory",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文一获奖类别"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper1_ccfLevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文一CCF等级"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper1_journalConference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文一期刊会议"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper1_paperName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文一名称"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper1_publicationTime",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文一发表时间"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper2_awardCategory",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文二获奖类别"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper2_ccfLevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文二CCF等级"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper2_journalConference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文二期刊会议"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper2_paperName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文二名称"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper2_publicationTime",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文二发表时间"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper3_awardCategory",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文三获奖类别"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper3_ccfLevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文三CCF等级"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper3_journalConference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文三期刊会议"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper3_paperName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文三名称"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_paper3_publicationTime",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="论文三发表时间"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_percentage",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="百分比"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="手机号码"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_photo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="照片"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_proofs",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="证明材料"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_rank",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="排名"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_secondChoice",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="第二志愿"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="状态"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_thirdChoice",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="第三志愿"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_tutor",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="导师"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_university",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="本科学校"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="_universityLevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="本科等级"
            ),
        ),
        migrations.AddField(
            model_name="apply",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apply",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
