# Generated by Django 4.2.19 on 2025-02-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0009_alter_apply_options_apply__applicationtype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apply",
            options={},
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_applicationType",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award1_awardName",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award1_awardRanking",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award1_awardTime",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award1_isLeader",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award1_levelRanking",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award2_awardName",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award2_awardRanking",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award2_awardTime",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award2_isLeader",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award2_levelRanking",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award3_awardName",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award3_awardRanking",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award3_awardTime",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award3_isLeader",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_award3_levelRanking",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_birthDate",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_email",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_firstAuthorLevel",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_firstChoice",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_gender",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_graduationYear",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_id",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_isAdjustable",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_isAwardCondition",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_isFilterCondition",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_isPaperCondition",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_isTopClass",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_major",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_majorCount",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_masterMajor",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_masterUniversity",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_masterUniversityLevel",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_name",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper1_awardCategory",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper1_ccfLevel",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper1_journalConference",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper1_paperName",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper1_publicationTime",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper2_awardCategory",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper2_ccfLevel",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper2_journalConference",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper2_paperName",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper2_publicationTime",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper3_awardCategory",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper3_ccfLevel",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper3_journalConference",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper3_paperName",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_paper3_publicationTime",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_percentage",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_phone",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_photo",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_proofs",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_rank",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_secondChoice",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_status",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_thirdChoice",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_tutor",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_university",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="_universityLevel",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="field",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="apply",
            name="applicationType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award1_awardName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award1_awardRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award1_awardTime",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award1_isLeader",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award1_levelRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_awardName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_awardRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_awardTime",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_isLeader",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_levelRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_awardName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_awardRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_awardTime",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_isLeader",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_levelRanking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="birthDate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="firstAuthorLevel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="firstChoice",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="graduationYear",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="isAdjustable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="isAwardCondition",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="isFilterCondition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="isPaperCondition",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="isTopClass",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="major",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="majorCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="masterMajor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="masterUniversity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="masterUniversityLevel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper1_ccfLevel",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper1_isFirst",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper1_journalConference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper1_paperName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper1_publicationTime",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper2_ccfLevel",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper2_isFirst",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper2_journalConference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper2_paperName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper2_publicationTime",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper3_ccfLevel",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper3_isFirst",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper3_journalConference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper3_paperName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="paper3_publicationTime",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="percentage",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="apply/"),
        ),
        migrations.AddField(
            model_name="apply",
            name="proofs",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="secondChoice",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="thirdChoice",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="tutor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="university",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="universityLevel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="apply",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
