# Generated by Django 4.2.19 on 2025-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0010_alter_apply_options_remove_apply__applicationtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="award1_awardTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apply",
            name="award2_awardTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apply",
            name="award3_awardTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apply",
            name="paper1_publicationTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apply",
            name="paper2_publicationTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apply",
            name="paper3_publicationTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
