# Generated by Django 4.2.19 on 2025-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0011_alter_apply_award1_awardtime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
