# Generated by Django 4.2.19 on 2025-02-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0012_apply_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="photo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
