# Generated by Django 4.2.19 on 2025-03-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0013_alter_apply_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="award1_contribution",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award2_contribution",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="award3_contribution",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
