# Generated by Django 5.1.2 on 2024-12-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_mytable_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="mytable",
        ),
        migrations.DeleteModel(
            name="Award",
        ),
        migrations.DeleteModel(
            name="Mytable",
        ),
        migrations.DeleteModel(
            name="Paper",
        ),
    ]
