# Generated by Django 4.2.19 on 2025-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Percent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pOfA", models.FloatField(blank=True, null=True)),
                ("pOfB", models.FloatField(blank=True, null=True)),
                ("pOfC", models.FloatField(blank=True, null=True)),
                ("pOfATop", models.FloatField(blank=True, null=True)),
                ("pOfBTop", models.FloatField(blank=True, null=True)),
                ("pOfCTop", models.FloatField(blank=True, null=True)),
                ("pOfATalent", models.FloatField(blank=True, null=True)),
                ("pOfBTalent", models.FloatField(blank=True, null=True)),
                ("pOfCTalent", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "percent",
            },
        ),
    ]
