# Generated by Django 5.1.4 on 2024-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_apply_award1_awardname_apply_award1_awardtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='birthDate',
            field=models.CharField(max_length=20),
        ),
    ]
